In [1]:
import numpy as np

In [10]:
# Задача 1: Создайте одномерный массив NumPy, содержащий первые 10 четных чисел.

np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
# Задача 2: Создайте двумерный массив размером 3x3, заполненный случайными целыми числами от 1 до 9.

random_matrix = np.random.randint(1, 10, size=(3, 3))
random_matrix

array([[7, 5, 8],
       [8, 1, 6],
       [2, 1, 4]])

In [16]:
# Задача 3: Найдите среднее, максимальное и минимальное значение в массиве из задачи 2.

maximum = np.max(random_matrix)
minimum = np.min(random_matrix)
mean = np.mean(random_matrix)
maximum, minimum, mean

(8, 1, 4.666666666666667)

In [19]:
# Задача 4: Создайте массив, содержащий последовательность чисел от 0 до 9. Потом измените порядок элементов на обратный.

mas = np.arange(10)
mas[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [23]:
# Задача 5: Создайте матрицу 5x5, где на главной диагонали будут стоять числа от 1 до 5, а вне диагонали - нули.

np.diag(np.arange(1, 6))

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [29]:
# Задача 6: Создайте два случайных массива размером 4x4 и выполните их поэлементное умножение.

first = np.random.rand(4, 4)
second = np.random.rand(4, 4)
product = first * second
product

array([[0.19513976, 0.04470701, 0.90722671, 0.29175877],
       [0.71398705, 0.23109753, 0.40776715, 0.01302964],
       [0.04667887, 0.0074316 , 0.4018483 , 0.34328251],
       [0.12967506, 0.00516474, 0.22470068, 0.00634105]])

In [34]:
# Задача 7: Найдите индексы максимальных значений в одномерном массиве.

mas = np.random.randint(1, 10, size=100)
np.where(mas == np.max(mas))

(array([ 5,  7,  9, 13, 15, 20, 21, 24, 64, 69, 72, 83, 89, 98]),)

In [42]:
# Задача 8: Создайте массив из 20 случайных чисел и найдите количество чисел, больше среднего значения этого массива.

mas = np.random.randint(1, 100, size=20)
mean_value = np.mean(mas)
np.sum(mas > mean_value)

9

In [51]:
# Задача 9: Создайте случайную матрицу 3x3 и найдите определитель этой матрицы.

matrix = np.random.randint(1, 10, size=(3, 3))
np.linalg.det(matrix)

8.99999999999999

In [54]:
# Задача 10: Создайте массив из чисел от 0 до 9. Используя маску, замените все значения меньше 5 на -1.

mas = np.random.randint(0, 10, size=100)
mas[mas < 5] = -1  # Замена значений меньше 5 на -1
mas

array([-1, -1, -1,  7,  9, -1, -1,  8, -1, -1, -1, -1, -1,  9,  8, -1,  7,
       -1, -1,  5,  7, -1,  6,  9, -1, -1,  6,  5, -1, -1, -1,  7,  5, -1,
        8,  8,  8, -1,  9,  5, -1, -1, -1,  8, -1, -1,  7, -1,  9,  5,  6,
       -1,  9, -1,  8,  7,  5, -1, -1, -1, -1, -1,  7, -1, -1,  6,  6, -1,
        8, -1, -1,  6,  6,  5,  5, -1, -1,  5,  5, -1, -1, -1, -1,  5,  9,
        5, -1, -1,  7,  7,  7,  8, -1, -1, -1,  9, -1,  6, -1, -1])